In [6]:
#Gram Smith Process
import numpy as np
u1=np.array([2,0,0])
u2=np.array([2,3,4])
u3=np.array([4,5,5])
w1=u1
v1=w1/np.linalg.norm(w1)
w2=u2-np.dot(u2,v1)*v1
v2=w2/np.linalg.norm(w2)
w3=u3-np.dot(u3,v1)*v1-np.dot(u3,v2)*v2
v3=w3/np.linalg.norm(w3)


In [4]:
v1,v2,v3

(array([1., 0., 0.]), array([0. , 0.6, 0.8]), array([ 0. ,  0.8, -0.6]))

In [8]:
matrixEx=np.array([[1,2],[3,4]])

In [10]:
matrixEx

array([[1, 2],
       [3, 4]])

In [12]:
matrixEx.T #transpose of a matrix

array([[1, 3],
       [2, 4]])

In [14]:
np.transpose(matrixEx)

array([[1, 3],
       [2, 4]])

In [16]:
matrixEx.transpose()

array([[1, 3],
       [2, 4]])

In [18]:
matrixEx.T.T


array([[1, 2],
       [3, 4]])

In [22]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [28]:
matrixEx2=np.array([[1,2,3],[3,4,6],[3,4,6]])
matrixEx2

array([[1, 2, 3],
       [3, 4, 6],
       [3, 4, 6]])

In [42]:
uppperTrianglur=np.triu(matrixEx2)

In [44]:
uppperTrianglur

array([[1, 2, 3],
       [0, 4, 6],
       [0, 0, 6]])

In [46]:
lowerTrianglur=np.tril(matrixEx2)

In [48]:
lowerTrianglur

array([[1, 0, 0],
       [3, 4, 0],
       [3, 4, 6]])

In [50]:
def is_symmetric(matrix):
    return np.array_equal(matrix,matrix.T)
is_symmetric(matrixEx2)

False

In [52]:
matrixSymmetric=np.array([[1,2,3],[2,4,5],[3,5,6]])
matrixSymmetric

array([[1, 2, 3],
       [2, 4, 5],
       [3, 5, 6]])

In [54]:
is_symmetric(matrixSymmetric)

True

In [96]:
import numpy as np


# Corrected asymmetric matrix
matrixAsymmetric = np.array([
    [0, 2, -3],
    [-2, 0, 4],
    [3, -4, 0]
])

print("Matrix A:")
print(matrixAsymmetric)
print("\nTranspose of A:")
print(matrixAsymmetric.T)
print("\nNegative Transpose of A:")
print(-matrixAsymmetric.T)

def is_Asymmetric(matrix):
    return np.array_equal(matrix, -matrix.T)

print("\nIs the matrix asymmetric?:", is_Asymmetric(matrixAsymmetric))


Matrix A:
[[ 0  2 -3]
 [-2  0  4]
 [ 3 -4  0]]

Transpose of A:
[[ 0 -2  3]
 [ 2  0 -4]
 [-3  4  0]]

Negative Transpose of A:
[[ 0  2 -3]
 [-2  0  4]
 [ 3 -4  0]]

Is the matrix asymmetric?: True


In [19]:
import numpy as np

class sampleClass:
    """
    A class to perform various checks on matrices.
    """

    def __init__(self, matrix=None, name="Default Object"): # added name parameter
        """
        Constructor for the sampleClass.

        Args:
            matrix (numpy.ndarray, optional): An initial matrix. Defaults to None.
            name (str, optional): A name for the object. Defaults to "Default Object".
        """
        self.matrix = matrix
        self.name = name # Storing the name

    @staticmethod
    def is_asymmetric(matrix):
        """Check if the matrix is asymmetric."""
        return np.array_equal(matrix, -matrix.T)

    @staticmethod
    def check_a_minus_b_equals_b_minus_a(matrix_a, matrix_b):
        """Check if A - B equals B - A and verify if it implies A = B."""
        diff_ab = matrix_a - matrix_b
        diff_ba = matrix_b - matrix_a
        if np.array_equal(diff_ab, diff_ba):
            return np.array_equal(matrix_a, matrix_b)
        return False

    def nonStaticMethod(self):
        """A non-static method."""
        print(f'Non Static method called by {self.name}') #Printing the name

# Examples of usage:
obj1 = sampleClass()  # Non-parameterized constructor
print(f"Object 1 name: {obj1.name}")
if obj1.matrix is None:
    print("🚀Object 1 has no initial matrix.")

matrix = np.array([[1, 2], [3, 4]])
obj2 = sampleClass(matrix, "Matrix Object")  # Parameterized constructor
print(f"Object 2 name: {obj2.name}")
print("⭐⭐Object 2's matrix:\n", obj2.matrix)

matrix2 = np.array([[0, 1], [-1, 0]])
obj3 = sampleClass(matrix2,"Asymmetric Matrix Object")
print(f"Object 3 name: {obj3.name}")
print("Is obj3's matrix asymmetric?", sampleClass.is_asymmetric(obj3.matrix))

obj1.nonStaticMethod()
obj2.nonStaticMethod()
obj3.nonStaticMethod()

Object 1 name: Default Object
🚀Object 1 has no initial matrix.
Object 2 name: Matrix Object
⭐⭐Object 2's matrix:
 [[1 2]
 [3 4]]
Object 3 name: Asymmetric Matrix Object
Is obj3's matrix asymmetric? True
Non Static method called by Default Object
Non Static method called by Matrix Object
Non Static method called by Asymmetric Matrix Object


In [126]:
A=np.array([[1,2,4],[3,4,6]])
B=np.array([[5,6],[7,8],[1,3]])
result=np.dot(A,B)
result2=np.dot(B,A)
'A.B',result,'B.A',result2

('A.B',
 array([[23, 34],
        [49, 68]]),
 'B.A',
 array([[23, 34, 56],
        [31, 46, 76],
        [10, 14, 22]]))

In [3]:
import numpy as np

# Define the matrices A and B
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

def transpose(X):
    return X.T

# Check transpose of the product
transpose_product = np.array_equal(transpose(np.dot(A, B)), np.dot(transpose(B), transpose(A)))
transpose_sum = np.array_equal(transpose(A + B), transpose(A) + transpose(B))
print("Transpose Product Equality:", transpose_product)
print("Transpose Sum Equality:", transpose_sum)
"""
Hence Proved
(𝐴+𝐵)^𝑇=𝐴^𝑇+𝐵^𝑇
(𝐴𝐵)^𝑇=𝐵^𝑇 𝐴^𝑇
"""


Transpose Product Equality: True
Transpose Sum Equality: True
